--- !ditz.rubyforge.org,2008-03-06/project 
name: blanco
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: blanco
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.2.0
  status: :released
  release_time: 2010-02-11 04:34:48.336087 Z
  log_events: 
  - - 2010-02-10 06:17:55.443879 Z
    - James Rowe <jnrowe@gmail.com>
    - created
    - ""
  - - 2010-02-11 04:34:48.336109 Z
    - James Rowe <jnrowe@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.3.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-02-11 03:17:44.815784 Z
    - James Rowe <jnrowe@gmail.com>
    - created
    - ""
